version: '3.1'
services:
  database:
    image: postgres:14.1-alpine
    container_name: transaction
    restart: always
    environment:
      - POSTGRES_DB=transaction
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
#      - POSTGRES_HOST_AUTH_METHOD="trust"
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:3.0.1
    container_name: grafana
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  grafana_data: {}

#  app:
#    build: .
#    image: app
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#      - 8000:8000
#    depends_on:
#      - database
