version: '3.1'
services:
  database:
    image: postgres:14.1-alpine
    container_name: transaction
    restart: always
    environment:
      - POSTGRES_DB=transaction
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
#      - POSTGRES_HOST_AUTH_METHOD="trust"
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
#  app:
#    build: .
#    image: app
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#      - 8000:8000
#    depends_on:
#      - database
